import Head from "next/head";
import Intro from "../Components/Intro";
import Services from "../Components/Services";
import Testimonials from "../Components/Testimonials";
import { data } from "../data";
import styles from "../styles/Home.module.css";

export default function Home({ services }) {
  console.log(services);
  return (
    <div>
      <Head>
        <title>Simple Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-2.svg" />
      </Head>
      <Intro />
      <Services services={services} />
      <Testimonials />
    </div>
  );
}

export const getStaticProps = async () => {
  const services = data;
  return {
    props: { services },
  };
};
